import 'dart:io';
import 'package:injectable/injectable.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

@lazySingleton
class PDFReportService {
  Future<String> generateDashboardReport({
    required String conceptName,
    required String fullName,
    required int totalPublications,
    required double avgCitations,
    required int totalCitations,
    required int activeYear,
    required String topJournal,
    required String topAuthor,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Academic Research Report', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                pw.Text(DateTime.now().toLocal().toString().substring(0, 10)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Text('Research Field: $conceptName', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.Text('Generated by: $fullName', style: pw.TextStyle(fontSize: 12)),
          pw.SizedBox(height: 30),
          pw.Text('Dashboard Analytics Overview', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.Divider(),
          pw.SizedBox(height: 10),
          pw.Bullet(text: 'Total Publications: $totalPublications'),
          pw.Bullet(text: 'Total Citations: $totalCitations'),
          pw.Bullet(text: 'Average Citations per Publication: ${avgCitations.toStringAsFixed(2)}'),
          pw.Bullet(text: 'Most Active Year: $activeYear'),
          pw.Bullet(text: 'Top Contributing Journal: $topJournal'),
          pw.Bullet(text: 'Top Contributing Author: $topAuthor'),
          pw.SizedBox(height: 40),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text('Powered by Journal Trend Analysis', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
          ),
        ],
      ),
    );

    // Save temporarily
    final output = await getTemporaryDirectory();
    final file = File('${output.path}/dashboard_report.pdf');
    if (await file.exists()) {
      await file.delete();
    }
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }
}
